name: if condition
on: push
jobs:
  run-test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3  
     - name: run test
       run: |
         for file in sample.txt text.txt
         do
           content=$(cat $file)
           if [["$content"==*"passed"]]; then
             echo "Test passed"
           else
             echo "Test failed"
           fi
         done
