name: Playwright test
on: 
  workflow_dispatch: 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        run: sudo apt update && sudo apt install -y nodejs npm
      - name: Install dependencies
        run: npm install
      - name: Install playwright
        run: npm install @playwright/test
      - name: Install browsers
        run: npx playwright install
      - name: Run test
        run: npx playwright test
