name: Example Test
on: 
  workflow_dispatch: 
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: environment setup
        run: echo "setting up environment"
  selenium-test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "running selenium tests....."
  playwright-test:
    runs-on: windows-latest
    steps:
      - run: echo "running playwright tests....."
  reports:
    needs: playwright-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Generating reports....."
