name: Read files demo
on: 
  push:
  workflow_dispatch: 
jobs:
  read-file:
    runs-on: ubuntu-latest
    steps:
      - name: get codE
        uses: actions/checkout@v3
      - name: read file
        run: |
          cat sample.txt
          cat text.txt
