name: Practice workflow
on: 
  push:
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo "build step"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Step2
        run: echo "test step"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Step3
        run: echo "deploy step"
  
